const GENERATE_POST_REQUEST = "GENERATE_POST_REQUEST";
const GENERATE_POST_ERROR = "GENERATE_POST_ERROR";
const GENERATE_POST_SUCCESS = "GENERATE_POST_SUCCESS";
const CLEAR_GENURL='CLEAR_GENURL'

const URLS_GET_REQUEST = "URLS_GET_REQUEST";
const URLS_GET_ERROR = "URLS_GET_ERROR";
const URLS_GET_SUCCESS = "URLS_GET_SUCCESS";

const URLS_EDIT_REQUEST = "URLS_EDIT_REQUEST";
const URLS_EDIT_ERROR = "URLS_EDIT_ERROR";
const URLS_EDIT_SUCCESS = "URLS_EDIT_SUCCESS";

const URLS_DELETE_REQUEST = "URLS_DELETE_REQUEST";
const URLS_DELETE_ERROR = "URLS_DELETE_ERROR";
const URLS_DELETE_SUCCESS = "URLS_DELETE_SUCCESS";

const DETAILS_GET_REQUEST = "DETAILS_GET_REQUEST";
const DETAILS_GET_ERROR = "DETAILS_GET_ERROR";
const DETAILS_GET_SUCCESS = "DETAILS_GET_SUCCESS";

const VISITORS_GET_REQUEST = "VISITORS_GET_REQUEST";
const VISITORS_GET_ERROR = "VISITORS_GET_ERROR";
const VISITORS_GET_SUCCESS = "VISITORS_GET_SUCCESS";

export {
  GENERATE_POST_ERROR,
  GENERATE_POST_REQUEST,
  GENERATE_POST_SUCCESS,
  CLEAR_GENURL,
  URLS_GET_ERROR,
  URLS_GET_REQUEST,
  URLS_GET_SUCCESS,
  URLS_DELETE_ERROR,
  URLS_DELETE_REQUEST,
  URLS_DELETE_SUCCESS,
  URLS_EDIT_ERROR,
  URLS_EDIT_REQUEST,
  URLS_EDIT_SUCCESS,
  DETAILS_GET_ERROR,
  DETAILS_GET_SUCCESS,
  DETAILS_GET_REQUEST,
  VISITORS_GET_ERROR,
  VISITORS_GET_REQUEST,
  VISITORS_GET_SUCCESS
};
