const LOGIN_POST_REQUEST = "LOGIN_POST_REQUEST";
const LOGIN_POST_SUCCESS = "LOGIN_POST_SUCCESS";
const LOGIN_POST_ERROR = "LOGIN_POST_ERROR";
const REGISTER_POST_REQUEST = "REGISTER_POST_REQUEST";
const REGISTER_POST_SUCCESS = "REGISTER_POST_SUCCESS";
const REGISTER_POST_ERROR = "REGISTER_POST_ERROR";
const LOGIN_LOGOUT = "LOGIN_LOGOUT";

export {
  LOGIN_LOGOUT,
  LOGIN_POST_ERROR,
  LOGIN_POST_REQUEST,
  LOGIN_POST_SUCCESS,
  REGISTER_POST_ERROR,
  REGISTER_POST_REQUEST,
  REGISTER_POST_SUCCESS,
};
