const DANGER_ALERT='DANGER_ALERT';
const SUCCESS_ALERT='SUCCESS_ALERT';
const INFO_ALERT='INFO_ALERT';
const ERROR_ALERT='ERROR_ALERT';
const CLEAR_ALERT='CLEAR_ALERT';

export {DANGER_ALERT,SUCCESS_ALERT,INFO_ALERT,CLEAR_ALERT,ERROR_ALERT};